experiment: PreliminaryTDA

seeds: [0, 1, 2]
device: "mps"
num_workers: 2

common_persistence:
  idx: [0, 2, 4, 6, 7, 9, 11, 13, 16]
  eps: 0.02

tasks:
  - name: mnist_clean
    dataset: MNIST
    transform: null
    power: 0.0
  - name: kmnist_clean
    dataset: KMNIST
    transform: null
    power: 0.0
  - name: fmnist_clean
    dataset: FMNIST
    transform: null
    power: 0.0
  - name: emnistb_clean
    dataset: EMNIST-B
    transform: null
    power: 0.0

methods:
  persistent_image:
    args:
      resolution: 28
      sigma2: 1.0
      weighting: linear
      weight_power: 1.0
      base_channels: 16
      dropout: 0.1
      lr: 0.0003
      batch_size: 128
      epochs: 50

  persistent_landscape:
    args:
      num_layers: 5
      resolution: 64
      base_channels: 16
      dropout: 0.1
      lr: 0.0003
      batch_size: 128
      epochs: 50

  persistent_silhouette:
    args:
      resolution: 64
      weighting: linear
      weight_power: 1.0
      base_channels: 16
      dropout: 0.1
      lr: 0.0003
      batch_size: 128
      epochs: 50

  deepsets:
    args:
      model: PHTS
      d_model: 128
      d_hidden: 192
      dropout: 0.1
      activation: GELU
      alpha: 0.0
      lr: 0.0001
      batch_size: 128
      epochs: 50

  persformer:
    args:
      model: PERSFORMER
      d_model: 96
      d_hidden: 192
      num_heads: 4
      num_layers: 3
      encoder_dropout: 0.1
      decoder_dropout: 0.1
      decoder_hidden_dims: "128,64"
      pooling_heads: 4
      norm: layer
      activation: GELU
      alpha: 0.0
      norm_first: true
      lr: 0.0005
      weight_decay: 0.0001
      warmup_epochs: 5
      eta_min: 0.000001
      batch_size: 64
      epochs: 50

  linear_persformer:
    args:
      model: LINEAR_PERSFORMER
      d_model: 96
      intermediate_size: 192
      num_hidden_layers: 3
      num_attention_heads: 4
      num_landmarks: 32
      encoder_dropout: 0.1
      decoder_dropout: 0.1
      decoder_hidden_dims: "128,64"
      pooling_heads: 4
      activation: GELU
      lr: 0.0005
      weight_decay: 0.0001
      warmup_epochs: 5
      eta_min: 0.000001
      batch_size: 64
      epochs: 50

  latent_persformer:
    args:
      model: LATENT_PERSFORMER
      d_model: 96
      d_latents: 128
      num_latents: 64
      num_blocks: 1
      num_self_attends_per_block: 2
      num_self_attention_heads: 4
      num_cross_attention_heads: 4
      cross_attention_widening_factor: 1
      self_attention_widening_factor: 1
      dropout: 0.1
      decoder_dropout: 0.1
      decoder_hidden_dims: "128,64"
      activation: GELU
      lr: 0.0005
      weight_decay: 0.0001
      warmup_epochs: 5
      eta_min: 0.000001
      batch_size: 64
      epochs: 50
