experiment: Invariance
datasets: [MNIST, EMNIST]
seeds: [0, 1, 2, 3, 4]
batch_size: 64
lr: 0.001
epochs: 100

transformations:
  - 
    name: GaussianNoise
    std: [0.005, 0.075, 0.01, 0.015, 0.02, 0.03, 0.05]
  - 
    name: GaussianBlur
    std: [1, 2, 4]
  - 
    name: RandomAffine
    std: [2, 4, 6, 8, 10]