experiment: Directions
datasets: [EMNIST-B]
seeds: [0]
batch_size: 128
lr: 0.001
epochs: 100
device: "mps"
filters: [
  [0], [1], [2], [3],
  [4], [5], [6], [7],
  [8], [9], [10], [11],
  [12], [13], [14], [15],
  [0, 16], [1, 16], [2, 16], [3, 16],
  [4, 16], [5, 16], [6, 16], [7, 16],
  [8, 16], [9, 16], [10, 16], [11, 16],
  [12, 16], [13, 16], [14, 16], [15, 16],
]