experiment: Invariance
seeds: [0, 1, 2, 3, 4]
device: "mps"
num_workers: 0

datasets: [MNIST, EMNIST-B]

transformations:
  - name: noise
    powers: [0.005, 0.075, 0.01, 0.015, 0.02, 0.03, 0.05]
  - name: blur
    powers: [1.0, 2.0, 4.0]
  - name: affine
    powers: [2.0, 4.0, 6.0, 8.0, 10.0]

methods:
  mlp:
    args:
      model: MLP
      lr: 0.001
      batch_size: 64
      epochs: 100
